// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStateStore creates a new instance of MockStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateStore {
	mock := &MockStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateStore is an autogenerated mock type for the StateStore type
type MockStateStore struct {
	mock.Mock
}

type MockStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateStore) EXPECT() *MockStateStore_Expecter {
	return &MockStateStore_Expecter{mock: &_m.Mock}
}

// Shutdown provides a mock function for the type MockStateStore
func (_mock *MockStateStore) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateStore_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockStateStore_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockStateStore_Expecter) Shutdown() *MockStateStore_Shutdown_Call {
	return &MockStateStore_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockStateStore_Shutdown_Call) Run(run func()) *MockStateStore_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateStore_Shutdown_Call) Return(err error) *MockStateStore_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateStore_Shutdown_Call) RunAndReturn(run func() error) *MockStateStore_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockStateStore
func (_mock *MockStateStore) Store(ctx context.Context, state string, value string, expiry time.Duration) error {
	ret := _mock.Called(ctx, state, value, expiry)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, state, value, expiry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateStore_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockStateStore_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - value string
//   - expiry time.Duration
func (_e *MockStateStore_Expecter) Store(ctx interface{}, state interface{}, value interface{}, expiry interface{}) *MockStateStore_Store_Call {
	return &MockStateStore_Store_Call{Call: _e.mock.On("Store", ctx, state, value, expiry)}
}

func (_c *MockStateStore_Store_Call) Run(run func(ctx context.Context, state string, value string, expiry time.Duration)) *MockStateStore_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStateStore_Store_Call) Return(err error) *MockStateStore_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateStore_Store_Call) RunAndReturn(run func(ctx context.Context, state string, value string, expiry time.Duration) error) *MockStateStore_Store_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAndDelete provides a mock function for the type MockStateStore
func (_mock *MockStateStore) VerifyAndDelete(ctx context.Context, state string) (string, error) {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAndDelete")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, state)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateStore_VerifyAndDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAndDelete'
type MockStateStore_VerifyAndDelete_Call struct {
	*mock.Call
}

// VerifyAndDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *MockStateStore_Expecter) VerifyAndDelete(ctx interface{}, state interface{}) *MockStateStore_VerifyAndDelete_Call {
	return &MockStateStore_VerifyAndDelete_Call{Call: _e.mock.On("VerifyAndDelete", ctx, state)}
}

func (_c *MockStateStore_VerifyAndDelete_Call) Run(run func(ctx context.Context, state string)) *MockStateStore_VerifyAndDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateStore_VerifyAndDelete_Call) Return(s string, err error) *MockStateStore_VerifyAndDelete_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStateStore_VerifyAndDelete_Call) RunAndReturn(run func(ctx context.Context, state string) (string, error)) *MockStateStore_VerifyAndDelete_Call {
	_c.Call.Return(run)
	return _c
}
