// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nats-io/nats.go/jetstream"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyValue creates a new instance of MockKeyValue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyValue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyValue {
	mock := &MockKeyValue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeyValue is an autogenerated mock type for the KeyValue type
type MockKeyValue struct {
	mock.Mock
}

type MockKeyValue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyValue) EXPECT() *MockKeyValue_Expecter {
	return &MockKeyValue_Expecter{mock: &_m.Mock}
}

// Bucket provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Bucket() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bucket")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockKeyValue_Bucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bucket'
type MockKeyValue_Bucket_Call struct {
	*mock.Call
}

// Bucket is a helper method to define mock.On call
func (_e *MockKeyValue_Expecter) Bucket() *MockKeyValue_Bucket_Call {
	return &MockKeyValue_Bucket_Call{Call: _e.mock.On("Bucket")}
}

func (_c *MockKeyValue_Bucket_Call) Run(run func()) *MockKeyValue_Bucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyValue_Bucket_Call) Return(s string) *MockKeyValue_Bucket_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockKeyValue_Bucket_Call) RunAndReturn(run func() string) *MockKeyValue_Bucket_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Create(ctx context.Context, key string, value []byte, opts ...jetstream.KVCreateOpt) (uint64, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, value, opts)
	} else {
		tmpRet = _mock.Called(ctx, key, value)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, ...jetstream.KVCreateOpt) (uint64, error)); ok {
		return returnFunc(ctx, key, value, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, ...jetstream.KVCreateOpt) uint64); ok {
		r0 = returnFunc(ctx, key, value, opts...)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, ...jetstream.KVCreateOpt) error); ok {
		r1 = returnFunc(ctx, key, value, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeyValue_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - opts ...jetstream.KVCreateOpt
func (_e *MockKeyValue_Expecter) Create(ctx any, key any, value any, opts ...any) *MockKeyValue_Create_Call {
	return &MockKeyValue_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, key, value}, opts...)...)}
}

func (_c *MockKeyValue_Create_Call) Run(run func(ctx context.Context, key string, value []byte, opts ...jetstream.KVCreateOpt)) *MockKeyValue_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []jetstream.KVCreateOpt
		var variadicArgs []jetstream.KVCreateOpt
		if len(args) > 3 {
			variadicArgs = args[3].([]jetstream.KVCreateOpt)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockKeyValue_Create_Call) Return(v uint64, err error) *MockKeyValue_Create_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKeyValue_Create_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, opts ...jetstream.KVCreateOpt) (uint64, error)) *MockKeyValue_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Delete(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...jetstream.KVDeleteOpt) error); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyValue_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeyValue_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...jetstream.KVDeleteOpt
func (_e *MockKeyValue_Expecter) Delete(ctx any, key any, opts ...any) *MockKeyValue_Delete_Call {
	return &MockKeyValue_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *MockKeyValue_Delete_Call) Run(run func(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt)) *MockKeyValue_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []jetstream.KVDeleteOpt
		var variadicArgs []jetstream.KVDeleteOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]jetstream.KVDeleteOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKeyValue_Delete_Call) Return(err error) *MockKeyValue_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyValue_Delete_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error) *MockKeyValue_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Get(ctx context.Context, key string) (jetstream.KeyValueEntry, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 jetstream.KeyValueEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (jetstream.KeyValueEntry, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) jetstream.KeyValueEntry); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyValueEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKeyValue_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockKeyValue_Expecter) Get(ctx any, key any) *MockKeyValue_Get_Call {
	return &MockKeyValue_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockKeyValue_Get_Call) Run(run func(ctx context.Context, key string)) *MockKeyValue_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyValue_Get_Call) Return(keyValueEntry jetstream.KeyValueEntry, err error) *MockKeyValue_Get_Call {
	_c.Call.Return(keyValueEntry, err)
	return _c
}

func (_c *MockKeyValue_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (jetstream.KeyValueEntry, error)) *MockKeyValue_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetRevision provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) GetRevision(ctx context.Context, key string, revision uint64) (jetstream.KeyValueEntry, error) {
	ret := _mock.Called(ctx, key, revision)

	if len(ret) == 0 {
		panic("no return value specified for GetRevision")
	}

	var r0 jetstream.KeyValueEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) (jetstream.KeyValueEntry, error)); ok {
		return returnFunc(ctx, key, revision)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) jetstream.KeyValueEntry); ok {
		r0 = returnFunc(ctx, key, revision)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyValueEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64) error); ok {
		r1 = returnFunc(ctx, key, revision)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_GetRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRevision'
type MockKeyValue_GetRevision_Call struct {
	*mock.Call
}

// GetRevision is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - revision uint64
func (_e *MockKeyValue_Expecter) GetRevision(ctx any, key any, revision any) *MockKeyValue_GetRevision_Call {
	return &MockKeyValue_GetRevision_Call{Call: _e.mock.On("GetRevision", ctx, key, revision)}
}

func (_c *MockKeyValue_GetRevision_Call) Run(run func(ctx context.Context, key string, revision uint64)) *MockKeyValue_GetRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyValue_GetRevision_Call) Return(keyValueEntry jetstream.KeyValueEntry, err error) *MockKeyValue_GetRevision_Call {
	_c.Call.Return(keyValueEntry, err)
	return _c
}

func (_c *MockKeyValue_GetRevision_Call) RunAndReturn(run func(ctx context.Context, key string, revision uint64) (jetstream.KeyValueEntry, error)) *MockKeyValue_GetRevision_Call {
	_c.Call.Return(run)
	return _c
}

// History provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) History(ctx context.Context, key string, opts ...jetstream.WatchOpt) ([]jetstream.KeyValueEntry, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for History")
	}

	var r0 []jetstream.KeyValueEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...jetstream.WatchOpt) ([]jetstream.KeyValueEntry, error)); ok {
		return returnFunc(ctx, key, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...jetstream.WatchOpt) []jetstream.KeyValueEntry); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jetstream.KeyValueEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...jetstream.WatchOpt) error); ok {
		r1 = returnFunc(ctx, key, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_History_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'History'
type MockKeyValue_History_Call struct {
	*mock.Call
}

// History is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...jetstream.WatchOpt
func (_e *MockKeyValue_Expecter) History(ctx any, key any, opts ...any) *MockKeyValue_History_Call {
	return &MockKeyValue_History_Call{Call: _e.mock.On("History",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *MockKeyValue_History_Call) Run(run func(ctx context.Context, key string, opts ...jetstream.WatchOpt)) *MockKeyValue_History_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []jetstream.WatchOpt
		var variadicArgs []jetstream.WatchOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]jetstream.WatchOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKeyValue_History_Call) Return(keyValueEntrys []jetstream.KeyValueEntry, err error) *MockKeyValue_History_Call {
	_c.Call.Return(keyValueEntrys, err)
	return _c
}

func (_c *MockKeyValue_History_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...jetstream.WatchOpt) ([]jetstream.KeyValueEntry, error)) *MockKeyValue_History_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Keys(ctx context.Context, opts ...jetstream.WatchOpt) ([]string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...jetstream.WatchOpt) ([]string, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...jetstream.WatchOpt) []string); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...jetstream.WatchOpt) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockKeyValue_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...jetstream.WatchOpt
func (_e *MockKeyValue_Expecter) Keys(ctx any, opts ...any) *MockKeyValue_Keys_Call {
	return &MockKeyValue_Keys_Call{Call: _e.mock.On("Keys",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockKeyValue_Keys_Call) Run(run func(ctx context.Context, opts ...jetstream.WatchOpt)) *MockKeyValue_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []jetstream.WatchOpt
		var variadicArgs []jetstream.WatchOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]jetstream.WatchOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockKeyValue_Keys_Call) Return(strings []string, err error) *MockKeyValue_Keys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockKeyValue_Keys_Call) RunAndReturn(run func(ctx context.Context, opts ...jetstream.WatchOpt) ([]string, error)) *MockKeyValue_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeys provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) ListKeys(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyLister, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListKeys")
	}

	var r0 jetstream.KeyLister
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...jetstream.WatchOpt) (jetstream.KeyLister, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...jetstream.WatchOpt) jetstream.KeyLister); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyLister)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...jetstream.WatchOpt) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_ListKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeys'
type MockKeyValue_ListKeys_Call struct {
	*mock.Call
}

// ListKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...jetstream.WatchOpt
func (_e *MockKeyValue_Expecter) ListKeys(ctx any, opts ...any) *MockKeyValue_ListKeys_Call {
	return &MockKeyValue_ListKeys_Call{Call: _e.mock.On("ListKeys",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockKeyValue_ListKeys_Call) Run(run func(ctx context.Context, opts ...jetstream.WatchOpt)) *MockKeyValue_ListKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []jetstream.WatchOpt
		var variadicArgs []jetstream.WatchOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]jetstream.WatchOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockKeyValue_ListKeys_Call) Return(keyLister jetstream.KeyLister, err error) *MockKeyValue_ListKeys_Call {
	_c.Call.Return(keyLister, err)
	return _c
}

func (_c *MockKeyValue_ListKeys_Call) RunAndReturn(run func(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyLister, error)) *MockKeyValue_ListKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeysFiltered provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) ListKeysFiltered(ctx context.Context, filters ...string) (jetstream.KeyLister, error) {
	var tmpRet mock.Arguments
	if len(filters) > 0 {
		tmpRet = _mock.Called(ctx, filters)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListKeysFiltered")
	}

	var r0 jetstream.KeyLister
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (jetstream.KeyLister, error)); ok {
		return returnFunc(ctx, filters...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) jetstream.KeyLister); ok {
		r0 = returnFunc(ctx, filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyLister)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, filters...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_ListKeysFiltered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeysFiltered'
type MockKeyValue_ListKeysFiltered_Call struct {
	*mock.Call
}

// ListKeysFiltered is a helper method to define mock.On call
//   - ctx context.Context
//   - filters ...string
func (_e *MockKeyValue_Expecter) ListKeysFiltered(ctx any, filters ...any) *MockKeyValue_ListKeysFiltered_Call {
	return &MockKeyValue_ListKeysFiltered_Call{Call: _e.mock.On("ListKeysFiltered",
		append([]any{ctx}, filters...)...)}
}

func (_c *MockKeyValue_ListKeysFiltered_Call) Run(run func(ctx context.Context, filters ...string)) *MockKeyValue_ListKeysFiltered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockKeyValue_ListKeysFiltered_Call) Return(keyLister jetstream.KeyLister, err error) *MockKeyValue_ListKeysFiltered_Call {
	_c.Call.Return(keyLister, err)
	return _c
}

func (_c *MockKeyValue_ListKeysFiltered_Call) RunAndReturn(run func(ctx context.Context, filters ...string) (jetstream.KeyLister, error)) *MockKeyValue_ListKeysFiltered_Call {
	_c.Call.Return(run)
	return _c
}

// Purge provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Purge(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, opts)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Purge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...jetstream.KVDeleteOpt) error); ok {
		r0 = returnFunc(ctx, key, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyValue_Purge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Purge'
type MockKeyValue_Purge_Call struct {
	*mock.Call
}

// Purge is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts ...jetstream.KVDeleteOpt
func (_e *MockKeyValue_Expecter) Purge(ctx any, key any, opts ...any) *MockKeyValue_Purge_Call {
	return &MockKeyValue_Purge_Call{Call: _e.mock.On("Purge",
		append([]any{ctx, key}, opts...)...)}
}

func (_c *MockKeyValue_Purge_Call) Run(run func(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt)) *MockKeyValue_Purge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []jetstream.KVDeleteOpt
		var variadicArgs []jetstream.KVDeleteOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]jetstream.KVDeleteOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKeyValue_Purge_Call) Return(err error) *MockKeyValue_Purge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyValue_Purge_Call) RunAndReturn(run func(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error) *MockKeyValue_Purge_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeDeletes provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) PurgeDeletes(ctx context.Context, opts ...jetstream.KVPurgeOpt) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PurgeDeletes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...jetstream.KVPurgeOpt) error); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyValue_PurgeDeletes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeDeletes'
type MockKeyValue_PurgeDeletes_Call struct {
	*mock.Call
}

// PurgeDeletes is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...jetstream.KVPurgeOpt
func (_e *MockKeyValue_Expecter) PurgeDeletes(ctx any, opts ...any) *MockKeyValue_PurgeDeletes_Call {
	return &MockKeyValue_PurgeDeletes_Call{Call: _e.mock.On("PurgeDeletes",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockKeyValue_PurgeDeletes_Call) Run(run func(ctx context.Context, opts ...jetstream.KVPurgeOpt)) *MockKeyValue_PurgeDeletes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []jetstream.KVPurgeOpt
		var variadicArgs []jetstream.KVPurgeOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]jetstream.KVPurgeOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockKeyValue_PurgeDeletes_Call) Return(err error) *MockKeyValue_PurgeDeletes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyValue_PurgeDeletes_Call) RunAndReturn(run func(ctx context.Context, opts ...jetstream.KVPurgeOpt) error) *MockKeyValue_PurgeDeletes_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Put(ctx context.Context, key string, value []byte) (uint64, error) {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (uint64, error)); ok {
		return returnFunc(ctx, key, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) uint64); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, key, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockKeyValue_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *MockKeyValue_Expecter) Put(ctx any, key any, value any) *MockKeyValue_Put_Call {
	return &MockKeyValue_Put_Call{Call: _e.mock.On("Put", ctx, key, value)}
}

func (_c *MockKeyValue_Put_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockKeyValue_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyValue_Put_Call) Return(v uint64, err error) *MockKeyValue_Put_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKeyValue_Put_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte) (uint64, error)) *MockKeyValue_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutString provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) PutString(ctx context.Context, key string, value string) (uint64, error) {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for PutString")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uint64, error)); ok {
		return returnFunc(ctx, key, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uint64); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_PutString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutString'
type MockKeyValue_PutString_Call struct {
	*mock.Call
}

// PutString is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockKeyValue_Expecter) PutString(ctx any, key any, value any) *MockKeyValue_PutString_Call {
	return &MockKeyValue_PutString_Call{Call: _e.mock.On("PutString", ctx, key, value)}
}

func (_c *MockKeyValue_PutString_Call) Run(run func(ctx context.Context, key string, value string)) *MockKeyValue_PutString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyValue_PutString_Call) Return(v uint64, err error) *MockKeyValue_PutString_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKeyValue_PutString_Call) RunAndReturn(run func(ctx context.Context, key string, value string) (uint64, error)) *MockKeyValue_PutString_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Status(ctx context.Context) (jetstream.KeyValueStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 jetstream.KeyValueStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (jetstream.KeyValueStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) jetstream.KeyValueStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyValueStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockKeyValue_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKeyValue_Expecter) Status(ctx any) *MockKeyValue_Status_Call {
	return &MockKeyValue_Status_Call{Call: _e.mock.On("Status", ctx)}
}

func (_c *MockKeyValue_Status_Call) Run(run func(ctx context.Context)) *MockKeyValue_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeyValue_Status_Call) Return(keyValueStatus jetstream.KeyValueStatus, err error) *MockKeyValue_Status_Call {
	_c.Call.Return(keyValueStatus, err)
	return _c
}

func (_c *MockKeyValue_Status_Call) RunAndReturn(run func(ctx context.Context) (jetstream.KeyValueStatus, error)) *MockKeyValue_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Update(ctx context.Context, key string, value []byte, revision uint64) (uint64, error) {
	ret := _mock.Called(ctx, key, value, revision)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, uint64) (uint64, error)); ok {
		return returnFunc(ctx, key, value, revision)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, uint64) uint64); ok {
		r0 = returnFunc(ctx, key, value, revision)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, uint64) error); ok {
		r1 = returnFunc(ctx, key, value, revision)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKeyValue_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - revision uint64
func (_e *MockKeyValue_Expecter) Update(ctx any, key any, value any, revision any) *MockKeyValue_Update_Call {
	return &MockKeyValue_Update_Call{Call: _e.mock.On("Update", ctx, key, value, revision)}
}

func (_c *MockKeyValue_Update_Call) Run(run func(ctx context.Context, key string, value []byte, revision uint64)) *MockKeyValue_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKeyValue_Update_Call) Return(v uint64, err error) *MockKeyValue_Update_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKeyValue_Update_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, revision uint64) (uint64, error)) *MockKeyValue_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) Watch(ctx context.Context, keys string, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, keys, opts)
	} else {
		tmpRet = _mock.Called(ctx, keys)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 jetstream.KeyWatcher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...jetstream.WatchOpt) (jetstream.KeyWatcher, error)); ok {
		return returnFunc(ctx, keys, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...jetstream.WatchOpt) jetstream.KeyWatcher); ok {
		r0 = returnFunc(ctx, keys, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyWatcher)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...jetstream.WatchOpt) error); ok {
		r1 = returnFunc(ctx, keys, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockKeyValue_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - keys string
//   - opts ...jetstream.WatchOpt
func (_e *MockKeyValue_Expecter) Watch(ctx any, keys any, opts ...any) *MockKeyValue_Watch_Call {
	return &MockKeyValue_Watch_Call{Call: _e.mock.On("Watch",
		append([]any{ctx, keys}, opts...)...)}
}

func (_c *MockKeyValue_Watch_Call) Run(run func(ctx context.Context, keys string, opts ...jetstream.WatchOpt)) *MockKeyValue_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []jetstream.WatchOpt
		var variadicArgs []jetstream.WatchOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]jetstream.WatchOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKeyValue_Watch_Call) Return(keyWatcher jetstream.KeyWatcher, err error) *MockKeyValue_Watch_Call {
	_c.Call.Return(keyWatcher, err)
	return _c
}

func (_c *MockKeyValue_Watch_Call) RunAndReturn(run func(ctx context.Context, keys string, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error)) *MockKeyValue_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// WatchAll provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) WatchAll(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WatchAll")
	}

	var r0 jetstream.KeyWatcher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...jetstream.WatchOpt) (jetstream.KeyWatcher, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...jetstream.WatchOpt) jetstream.KeyWatcher); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyWatcher)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...jetstream.WatchOpt) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_WatchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchAll'
type MockKeyValue_WatchAll_Call struct {
	*mock.Call
}

// WatchAll is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...jetstream.WatchOpt
func (_e *MockKeyValue_Expecter) WatchAll(ctx any, opts ...any) *MockKeyValue_WatchAll_Call {
	return &MockKeyValue_WatchAll_Call{Call: _e.mock.On("WatchAll",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockKeyValue_WatchAll_Call) Run(run func(ctx context.Context, opts ...jetstream.WatchOpt)) *MockKeyValue_WatchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []jetstream.WatchOpt
		var variadicArgs []jetstream.WatchOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]jetstream.WatchOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockKeyValue_WatchAll_Call) Return(keyWatcher jetstream.KeyWatcher, err error) *MockKeyValue_WatchAll_Call {
	_c.Call.Return(keyWatcher, err)
	return _c
}

func (_c *MockKeyValue_WatchAll_Call) RunAndReturn(run func(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error)) *MockKeyValue_WatchAll_Call {
	_c.Call.Return(run)
	return _c
}

// WatchFiltered provides a mock function for the type MockKeyValue
func (_mock *MockKeyValue) WatchFiltered(ctx context.Context, keys []string, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, keys, opts)
	} else {
		tmpRet = _mock.Called(ctx, keys)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WatchFiltered")
	}

	var r0 jetstream.KeyWatcher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...jetstream.WatchOpt) (jetstream.KeyWatcher, error)); ok {
		return returnFunc(ctx, keys, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...jetstream.WatchOpt) jetstream.KeyWatcher); ok {
		r0 = returnFunc(ctx, keys, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyWatcher)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ...jetstream.WatchOpt) error); ok {
		r1 = returnFunc(ctx, keys, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyValue_WatchFiltered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchFiltered'
type MockKeyValue_WatchFiltered_Call struct {
	*mock.Call
}

// WatchFiltered is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
//   - opts ...jetstream.WatchOpt
func (_e *MockKeyValue_Expecter) WatchFiltered(ctx any, keys any, opts ...any) *MockKeyValue_WatchFiltered_Call {
	return &MockKeyValue_WatchFiltered_Call{Call: _e.mock.On("WatchFiltered",
		append([]any{ctx, keys}, opts...)...)}
}

func (_c *MockKeyValue_WatchFiltered_Call) Run(run func(ctx context.Context, keys []string, opts ...jetstream.WatchOpt)) *MockKeyValue_WatchFiltered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []jetstream.WatchOpt
		var variadicArgs []jetstream.WatchOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]jetstream.WatchOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKeyValue_WatchFiltered_Call) Return(keyWatcher jetstream.KeyWatcher, err error) *MockKeyValue_WatchFiltered_Call {
	_c.Call.Return(keyWatcher, err)
	return _c
}

func (_c *MockKeyValue_WatchFiltered_Call) RunAndReturn(run func(ctx context.Context, keys []string, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error)) *MockKeyValue_WatchFiltered_Call {
	_c.Call.Return(run)
	return _c
}
