// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yunobar/album/internal/core/mail"
)

// NewMockMailService creates a new instance of MockMailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailService {
	mock := &MockMailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailService is an autogenerated mock type for the MailService type
type MockMailService struct {
	mock.Mock
}

type MockMailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailService) EXPECT() *MockMailService_Expecter {
	return &MockMailService_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockMailService
func (_mock *MockMailService) Send(ctx context.Context, msg mail.MailMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mail.MailMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMailService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg mail.MailMessage
func (_e *MockMailService_Expecter) Send(ctx interface{}, msg interface{}) *MockMailService_Send_Call {
	return &MockMailService_Send_Call{Call: _e.mock.On("Send", ctx, msg)}
}

func (_c *MockMailService_Send_Call) Run(run func(ctx context.Context, msg mail.MailMessage)) *MockMailService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mail.MailMessage
		if args[1] != nil {
			arg1 = args[1].(mail.MailMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMailService_Send_Call) Return(err error) *MockMailService_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailService_Send_Call) RunAndReturn(run func(ctx context.Context, msg mail.MailMessage) error) *MockMailService_Send_Call {
	_c.Call.Return(run)
	return _c
}
