// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/yunobar/album/internal/domain/dto"
)

// NewMockProfileService creates a new instance of MockProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileService {
	mock := &MockProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileService is an autogenerated mock type for the ProfileService type
type MockProfileService struct {
	mock.Mock
}

type MockProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileService) EXPECT() *MockProfileService_Expecter {
	return &MockProfileService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProfileService
func (_mock *MockProfileService) Create(ctx context.Context, request dto.NewProfileRequest) (dto.ProfileResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.NewProfileRequest) (dto.ProfileResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.NewProfileRequest) dto.ProfileResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.ProfileResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.NewProfileRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProfileService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request dto.NewProfileRequest
func (_e *MockProfileService_Expecter) Create(ctx interface{}, request interface{}) *MockProfileService_Create_Call {
	return &MockProfileService_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockProfileService_Create_Call) Run(run func(ctx context.Context, request dto.NewProfileRequest)) *MockProfileService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.NewProfileRequest
		if args[1] != nil {
			arg1 = args[1].(dto.NewProfileRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_Create_Call) Return(profileResponse dto.ProfileResponse, err error) *MockProfileService_Create_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileService_Create_Call) RunAndReturn(run func(ctx context.Context, request dto.NewProfileRequest) (dto.ProfileResponse, error)) *MockProfileService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetByID(ctx context.Context, id uuid.UUID) (dto.ProfileResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.ProfileResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.ProfileResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.ProfileResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProfileService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProfileService_Expecter) GetByID(ctx interface{}, id interface{}) *MockProfileService_GetByID_Call {
	return &MockProfileService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProfileService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProfileService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetByID_Call) Return(profileResponse dto.ProfileResponse, err error) *MockProfileService_GetByID_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (dto.ProfileResponse, error)) *MockProfileService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileIDByUserID provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetProfileIDByUserID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileIDByUserID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetProfileIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileIDByUserID'
type MockProfileService_GetProfileIDByUserID_Call struct {
	*mock.Call
}

// GetProfileIDByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockProfileService_Expecter) GetProfileIDByUserID(ctx interface{}, userID interface{}) *MockProfileService_GetProfileIDByUserID_Call {
	return &MockProfileService_GetProfileIDByUserID_Call{Call: _e.mock.On("GetProfileIDByUserID", ctx, userID)}
}

func (_c *MockProfileService_GetProfileIDByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockProfileService_GetProfileIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetProfileIDByUserID_Call) Return(uUID uuid.UUID, err error) *MockProfileService_GetProfileIDByUserID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockProfileService_GetProfileIDByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)) *MockProfileService_GetProfileIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProfileService
func (_mock *MockProfileService) Update(ctx context.Context, req dto.UpdateProfileRequest) (dto.ProfileResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateProfileRequest) (dto.ProfileResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateProfileRequest) dto.ProfileResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.ProfileResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.UpdateProfileRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProfileService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.UpdateProfileRequest
func (_e *MockProfileService_Expecter) Update(ctx interface{}, req interface{}) *MockProfileService_Update_Call {
	return &MockProfileService_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockProfileService_Update_Call) Run(run func(ctx context.Context, req dto.UpdateProfileRequest)) *MockProfileService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UpdateProfileRequest
		if args[1] != nil {
			arg1 = args[1].(dto.UpdateProfileRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_Update_Call) Return(profileResponse dto.ProfileResponse, err error) *MockProfileService_Update_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileService_Update_Call) RunAndReturn(run func(ctx context.Context, req dto.UpdateProfileRequest) (dto.ProfileResponse, error)) *MockProfileService_Update_Call {
	_c.Call.Return(run)
	return _c
}
