// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache[T] {
	mock := &MockCache[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache[T any] struct {
	mock.Mock
}

type MockCache_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockCache[T]) EXPECT() *MockCache_Expecter[T] {
	return &MockCache_Expecter[T]{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCache
func (_mock *MockCache[T]) Delete(key string) {
	_mock.Called(key)
	return
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *MockCache_Expecter[T]) Delete(key any) *MockCache_Delete_Call[T] {
	return &MockCache_Delete_Call[T]{Call: _e.mock.On("Delete", key)}
}

func (_c *MockCache_Delete_Call[T]) Run(run func(key string)) *MockCache_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Delete_Call[T]) Return() *MockCache_Delete_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Delete_Call[T]) RunAndReturn(run func(key string)) *MockCache_Delete_Call[T] {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache[T]) Get(key string, fallbackFunc func(string) (T, bool)) (T, bool) {
	ret := _mock.Called(key, fallbackFunc)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, func(string) (T, bool)) (T, bool)); ok {
		return returnFunc(key, fallbackFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(string, func(string) (T, bool)) T); ok {
		r0 = returnFunc(key, fallbackFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, func(string) (T, bool)) bool); ok {
		r1 = returnFunc(key, fallbackFunc)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
//   - fallbackFunc func(string) (T, bool)
func (_e *MockCache_Expecter[T]) Get(key any, fallbackFunc any) *MockCache_Get_Call[T] {
	return &MockCache_Get_Call[T]{Call: _e.mock.On("Get", key, fallbackFunc)}
}

func (_c *MockCache_Get_Call[T]) Run(run func(key string, fallbackFunc func(string) (T, bool))) *MockCache_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(string) (T, bool)
		if args[1] != nil {
			arg1 = args[1].(func(string) (T, bool))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call[T]) Return(v T, b bool) *MockCache_Get_Call[T] {
	_c.Call.Return(v, b)
	return _c
}

func (_c *MockCache_Get_Call[T]) RunAndReturn(run func(key string, fallbackFunc func(string) (T, bool)) (T, bool)) *MockCache_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockCache
func (_mock *MockCache[T]) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockCache_Shutdown_Call[T any] struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockCache_Expecter[T]) Shutdown() *MockCache_Shutdown_Call[T] {
	return &MockCache_Shutdown_Call[T]{Call: _e.mock.On("Shutdown")}
}

func (_c *MockCache_Shutdown_Call[T]) Run(run func()) *MockCache_Shutdown_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Shutdown_Call[T]) Return(err error) *MockCache_Shutdown_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Shutdown_Call[T]) RunAndReturn(run func() error) *MockCache_Shutdown_Call[T] {
	_c.Call.Return(run)
	return _c
}
