// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/itsLeonB/go-crud"
	mock "github.com/stretchr/testify/mock"
	"github.com/yunobar/album/internal/domain/entity"
	"github.com/yunobar/album/internal/domain/repository"
	"gorm.io/gorm"
)

// NewMockGroupRepository creates a new instance of MockGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupRepository {
	mock := &MockGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupRepository is an autogenerated mock type for the GroupRepository type
type MockGroupRepository struct {
	mock.Mock
}

type MockGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupRepository) EXPECT() *MockGroupRepository_Expecter {
	return &MockGroupRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) Delete(ctx context.Context, model entity.Group) error {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) error); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGroupRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.Group
func (_e *MockGroupRepository_Expecter) Delete(ctx any, model any) *MockGroupRepository_Delete_Call {
	return &MockGroupRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockGroupRepository_Delete_Call) Run(run func(ctx context.Context, model entity.Group)) *MockGroupRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Group
		if args[1] != nil {
			arg1 = args[1].(entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_Delete_Call) Return(err error) *MockGroupRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, model entity.Group) error) *MockGroupRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) DeleteMany(ctx context.Context, models []entity.Group) error {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Group) error); ok {
		r0 = returnFunc(ctx, models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockGroupRepository_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.Group
func (_e *MockGroupRepository_Expecter) DeleteMany(ctx any, models any) *MockGroupRepository_DeleteMany_Call {
	return &MockGroupRepository_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockGroupRepository_DeleteMany_Call) Run(run func(ctx context.Context, models []entity.Group)) *MockGroupRepository_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Group
		if args[1] != nil {
			arg1 = args[1].([]entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_DeleteMany_Call) Return(err error) *MockGroupRepository_DeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupRepository_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, models []entity.Group) error) *MockGroupRepository_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveSession provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) FindActiveSession(ctx context.Context, groupID uuid.UUID, profileID uuid.UUID) (*repository.ActiveSession, error) {
	ret := _mock.Called(ctx, groupID, profileID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveSession")
	}

	var r0 *repository.ActiveSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*repository.ActiveSession, error)); ok {
		return returnFunc(ctx, groupID, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *repository.ActiveSession); ok {
		r0 = returnFunc(ctx, groupID, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ActiveSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, groupID, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_FindActiveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveSession'
type MockGroupRepository_FindActiveSession_Call struct {
	*mock.Call
}

// FindActiveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - profileID uuid.UUID
func (_e *MockGroupRepository_Expecter) FindActiveSession(ctx any, groupID any, profileID any) *MockGroupRepository_FindActiveSession_Call {
	return &MockGroupRepository_FindActiveSession_Call{Call: _e.mock.On("FindActiveSession", ctx, groupID, profileID)}
}

func (_c *MockGroupRepository_FindActiveSession_Call) Run(run func(ctx context.Context, groupID uuid.UUID, profileID uuid.UUID)) *MockGroupRepository_FindActiveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupRepository_FindActiveSession_Call) Return(activeSession *repository.ActiveSession, err error) *MockGroupRepository_FindActiveSession_Call {
	_c.Call.Return(activeSession, err)
	return _c
}

func (_c *MockGroupRepository_FindActiveSession_Call) RunAndReturn(run func(ctx context.Context, groupID uuid.UUID, profileID uuid.UUID) (*repository.ActiveSession, error)) *MockGroupRepository_FindActiveSession_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) FindAll(ctx context.Context, spec crud.Specification[entity.Group]) ([]entity.Group, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.Group]) ([]entity.Group, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.Group]) []entity.Group); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.Group]) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockGroupRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.Group]
func (_e *MockGroupRepository_Expecter) FindAll(ctx any, spec any) *MockGroupRepository_FindAll_Call {
	return &MockGroupRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockGroupRepository_FindAll_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.Group])) *MockGroupRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crud.Specification[entity.Group]
		if args[1] != nil {
			arg1 = args[1].(crud.Specification[entity.Group])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_FindAll_Call) Return(groups []entity.Group, err error) *MockGroupRepository_FindAll_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, spec crud.Specification[entity.Group]) ([]entity.Group, error)) *MockGroupRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.Group]) (entity.Group, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.Group]) (entity.Group, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[entity.Group]) entity.Group); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(entity.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crud.Specification[entity.Group]) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockGroupRepository_FindFirst_Call struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[entity.Group]
func (_e *MockGroupRepository_Expecter) FindFirst(ctx any, spec any) *MockGroupRepository_FindFirst_Call {
	return &MockGroupRepository_FindFirst_Call{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockGroupRepository_FindFirst_Call) Run(run func(ctx context.Context, spec crud.Specification[entity.Group])) *MockGroupRepository_FindFirst_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crud.Specification[entity.Group]
		if args[1] != nil {
			arg1 = args[1].(crud.Specification[entity.Group])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_FindFirst_Call) Return(group entity.Group, err error) *MockGroupRepository_FindFirst_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupRepository_FindFirst_Call) RunAndReturn(run func(ctx context.Context, spec crud.Specification[entity.Group]) (entity.Group, error)) *MockGroupRepository_FindFirst_Call {
	_c.Call.Return(run)
	return _c
}

// FindMergedContentIDs provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) FindMergedContentIDs(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for FindMergedContentIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_FindMergedContentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMergedContentIDs'
type MockGroupRepository_FindMergedContentIDs_Call struct {
	*mock.Call
}

// FindMergedContentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockGroupRepository_Expecter) FindMergedContentIDs(ctx any, groupID any) *MockGroupRepository_FindMergedContentIDs_Call {
	return &MockGroupRepository_FindMergedContentIDs_Call{Call: _e.mock.On("FindMergedContentIDs", ctx, groupID)}
}

func (_c *MockGroupRepository_FindMergedContentIDs_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockGroupRepository_FindMergedContentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_FindMergedContentIDs_Call) Return(uUIDs []uuid.UUID, err error) *MockGroupRepository_FindMergedContentIDs_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockGroupRepository_FindMergedContentIDs_Call) RunAndReturn(run func(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error)) *MockGroupRepository_FindMergedContentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockGroupRepository_GetGormInstance_Call struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGroupRepository_Expecter) GetGormInstance(ctx any) *MockGroupRepository_GetGormInstance_Call {
	return &MockGroupRepository_GetGormInstance_Call{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockGroupRepository_GetGormInstance_Call) Run(run func(ctx context.Context)) *MockGroupRepository_GetGormInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGroupRepository_GetGormInstance_Call) Return(dB *gorm.DB, err error) *MockGroupRepository_GetGormInstance_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *MockGroupRepository_GetGormInstance_Call) RunAndReturn(run func(ctx context.Context) (*gorm.DB, error)) *MockGroupRepository_GetGormInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) Insert(ctx context.Context, model entity.Group) (entity.Group, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) (entity.Group, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) entity.Group); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Group) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockGroupRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.Group
func (_e *MockGroupRepository_Expecter) Insert(ctx any, model any) *MockGroupRepository_Insert_Call {
	return &MockGroupRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, model)}
}

func (_c *MockGroupRepository_Insert_Call) Run(run func(ctx context.Context, model entity.Group)) *MockGroupRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Group
		if args[1] != nil {
			arg1 = args[1].(entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_Insert_Call) Return(group entity.Group, err error) *MockGroupRepository_Insert_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, model entity.Group) (entity.Group, error)) *MockGroupRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) InsertMany(ctx context.Context, models []entity.Group) ([]entity.Group, error) {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Group) ([]entity.Group, error)); ok {
		return returnFunc(ctx, models)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Group) []entity.Group); ok {
		r0 = returnFunc(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []entity.Group) error); ok {
		r1 = returnFunc(ctx, models)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockGroupRepository_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.Group
func (_e *MockGroupRepository_Expecter) InsertMany(ctx any, models any) *MockGroupRepository_InsertMany_Call {
	return &MockGroupRepository_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockGroupRepository_InsertMany_Call) Run(run func(ctx context.Context, models []entity.Group)) *MockGroupRepository_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Group
		if args[1] != nil {
			arg1 = args[1].([]entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_InsertMany_Call) Return(groups []entity.Group, err error) *MockGroupRepository_InsertMany_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupRepository_InsertMany_Call) RunAndReturn(run func(ctx context.Context, models []entity.Group) ([]entity.Group, error)) *MockGroupRepository_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) SaveMany(ctx context.Context, models []entity.Group) ([]entity.Group, error) {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Group) ([]entity.Group, error)); ok {
		return returnFunc(ctx, models)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Group) []entity.Group); ok {
		r0 = returnFunc(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []entity.Group) error); ok {
		r1 = returnFunc(ctx, models)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockGroupRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []entity.Group
func (_e *MockGroupRepository_Expecter) SaveMany(ctx any, models any) *MockGroupRepository_SaveMany_Call {
	return &MockGroupRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockGroupRepository_SaveMany_Call) Run(run func(ctx context.Context, models []entity.Group)) *MockGroupRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Group
		if args[1] != nil {
			arg1 = args[1].([]entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_SaveMany_Call) Return(groups []entity.Group, err error) *MockGroupRepository_SaveMany_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupRepository_SaveMany_Call) RunAndReturn(run func(ctx context.Context, models []entity.Group) ([]entity.Group, error)) *MockGroupRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockGroupRepository
func (_mock *MockGroupRepository) Update(ctx context.Context, model entity.Group) (entity.Group, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) (entity.Group, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) entity.Group); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(entity.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Group) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGroupRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model entity.Group
func (_e *MockGroupRepository_Expecter) Update(ctx any, model any) *MockGroupRepository_Update_Call {
	return &MockGroupRepository_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockGroupRepository_Update_Call) Run(run func(ctx context.Context, model entity.Group)) *MockGroupRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Group
		if args[1] != nil {
			arg1 = args[1].(entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupRepository_Update_Call) Return(group entity.Group, err error) *MockGroupRepository_Update_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupRepository_Update_Call) RunAndReturn(run func(ctx context.Context, model entity.Group) (entity.Group, error)) *MockGroupRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
