// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockTransactor
func (_mock *MockTransactor) Begin(ctx context.Context) (context.Context, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactor_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockTransactor_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactor_Expecter) Begin(ctx interface{}) *MockTransactor_Begin_Call {
	return &MockTransactor_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockTransactor_Begin_Call) Run(run func(ctx context.Context)) *MockTransactor_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactor_Begin_Call) Return(context1 context.Context, err error) *MockTransactor_Begin_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *MockTransactor_Begin_Call) RunAndReturn(run func(ctx context.Context) (context.Context, error)) *MockTransactor_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockTransactor
func (_mock *MockTransactor) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTransactor_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactor_Expecter) Commit(ctx interface{}) *MockTransactor_Commit_Call {
	return &MockTransactor_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockTransactor_Commit_Call) Run(run func(ctx context.Context)) *MockTransactor_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactor_Commit_Call) Return(err error) *MockTransactor_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockTransactor_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockTransactor
func (_mock *MockTransactor) Rollback(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTransactor_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTransactor_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactor_Expecter) Rollback(ctx interface{}) *MockTransactor_Rollback_Call {
	return &MockTransactor_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockTransactor_Rollback_Call) Run(run func(ctx context.Context)) *MockTransactor_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactor_Rollback_Call) Return() *MockTransactor_Rollback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransactor_Rollback_Call) RunAndReturn(run func(ctx context.Context)) *MockTransactor_Rollback_Call {
	_c.Run(run)
	return _c
}

// WithinTransaction provides a mock function for the type MockTransactor
func (_mock *MockTransactor) WithinTransaction(ctx context.Context, serviceFn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, serviceFn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, serviceFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTransactor_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceFn func(ctx context.Context) error
func (_e *MockTransactor_Expecter) WithinTransaction(ctx interface{}, serviceFn interface{}) *MockTransactor_WithinTransaction_Call {
	return &MockTransactor_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, serviceFn)}
}

func (_c *MockTransactor_WithinTransaction_Call) Run(run func(ctx context.Context, serviceFn func(ctx context.Context) error)) *MockTransactor_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactor_WithinTransaction_Call) Return(err error) *MockTransactor_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, serviceFn func(ctx context.Context) error) error) *MockTransactor_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}
