// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/itsLeonB/go-crud"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository[T] {
	mock := &MockRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository[T any] struct {
	mock.Mock
}

type MockRepository_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockRepository[T]) EXPECT() *MockRepository_Expecter[T] {
	return &MockRepository_Expecter[T]{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Delete(ctx context.Context, model T) error {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model T
func (_e *MockRepository_Expecter[T]) Delete(ctx any, model any) *MockRepository_Delete_Call[T] {
	return &MockRepository_Delete_Call[T]{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockRepository_Delete_Call[T]) Run(run func(ctx context.Context, model T)) *MockRepository_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call[T]) Return(err error) *MockRepository_Delete_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call[T]) RunAndReturn(run func(ctx context.Context, model T) error) *MockRepository_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) DeleteMany(ctx context.Context, models []T) error {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T) error); ok {
		r0 = returnFunc(ctx, models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockRepository_DeleteMany_Call[T any] struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []T
func (_e *MockRepository_Expecter[T]) DeleteMany(ctx any, models any) *MockRepository_DeleteMany_Call[T] {
	return &MockRepository_DeleteMany_Call[T]{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockRepository_DeleteMany_Call[T]) Run(run func(ctx context.Context, models []T)) *MockRepository_DeleteMany_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []T
		if args[1] != nil {
			arg1 = args[1].([]T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteMany_Call[T]) Return(err error) *MockRepository_DeleteMany_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteMany_Call[T]) RunAndReturn(run func(ctx context.Context, models []T) error) *MockRepository_DeleteMany_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) FindAll(ctx context.Context, spec crud.Specification[T]) ([]T, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[T]) ([]T, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[T]) []T); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crud.Specification[T]) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call[T any] struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[T]
func (_e *MockRepository_Expecter[T]) FindAll(ctx any, spec any) *MockRepository_FindAll_Call[T] {
	return &MockRepository_FindAll_Call[T]{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockRepository_FindAll_Call[T]) Run(run func(ctx context.Context, spec crud.Specification[T])) *MockRepository_FindAll_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crud.Specification[T]
		if args[1] != nil {
			arg1 = args[1].(crud.Specification[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindAll_Call[T]) Return(vs []T, err error) *MockRepository_FindAll_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockRepository_FindAll_Call[T]) RunAndReturn(run func(ctx context.Context, spec crud.Specification[T]) ([]T, error)) *MockRepository_FindAll_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) FindFirst(ctx context.Context, spec crud.Specification[T]) (T, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[T]) (T, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[T]) T); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crud.Specification[T]) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockRepository_FindFirst_Call[T any] struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[T]
func (_e *MockRepository_Expecter[T]) FindFirst(ctx any, spec any) *MockRepository_FindFirst_Call[T] {
	return &MockRepository_FindFirst_Call[T]{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockRepository_FindFirst_Call[T]) Run(run func(ctx context.Context, spec crud.Specification[T])) *MockRepository_FindFirst_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crud.Specification[T]
		if args[1] != nil {
			arg1 = args[1].(crud.Specification[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindFirst_Call[T]) Return(v T, err error) *MockRepository_FindFirst_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_FindFirst_Call[T]) RunAndReturn(run func(ctx context.Context, spec crud.Specification[T]) (T, error)) *MockRepository_FindFirst_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockRepository_GetGormInstance_Call[T any] struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter[T]) GetGormInstance(ctx any) *MockRepository_GetGormInstance_Call[T] {
	return &MockRepository_GetGormInstance_Call[T]{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockRepository_GetGormInstance_Call[T]) Run(run func(ctx context.Context)) *MockRepository_GetGormInstance_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetGormInstance_Call[T]) Return(dB *gorm.DB, err error) *MockRepository_GetGormInstance_Call[T] {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *MockRepository_GetGormInstance_Call[T]) RunAndReturn(run func(ctx context.Context) (*gorm.DB, error)) *MockRepository_GetGormInstance_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Insert(ctx context.Context, model T) (T, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) (T, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) T); ok {
		r0 = returnFunc(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call[T any] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model T
func (_e *MockRepository_Expecter[T]) Insert(ctx any, model any) *MockRepository_Insert_Call[T] {
	return &MockRepository_Insert_Call[T]{Call: _e.mock.On("Insert", ctx, model)}
}

func (_c *MockRepository_Insert_Call[T]) Run(run func(ctx context.Context, model T)) *MockRepository_Insert_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Insert_Call[T]) Return(v T, err error) *MockRepository_Insert_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_Insert_Call[T]) RunAndReturn(run func(ctx context.Context, model T) (T, error)) *MockRepository_Insert_Call[T] {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) InsertMany(ctx context.Context, models []T) ([]T, error) {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T) ([]T, error)); ok {
		return returnFunc(ctx, models)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T) []T); ok {
		r0 = returnFunc(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []T) error); ok {
		r1 = returnFunc(ctx, models)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockRepository_InsertMany_Call[T any] struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []T
func (_e *MockRepository_Expecter[T]) InsertMany(ctx any, models any) *MockRepository_InsertMany_Call[T] {
	return &MockRepository_InsertMany_Call[T]{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockRepository_InsertMany_Call[T]) Run(run func(ctx context.Context, models []T)) *MockRepository_InsertMany_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []T
		if args[1] != nil {
			arg1 = args[1].([]T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertMany_Call[T]) Return(vs []T, err error) *MockRepository_InsertMany_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockRepository_InsertMany_Call[T]) RunAndReturn(run func(ctx context.Context, models []T) ([]T, error)) *MockRepository_InsertMany_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) SaveMany(ctx context.Context, models []T) ([]T, error) {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T) ([]T, error)); ok {
		return returnFunc(ctx, models)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T) []T); ok {
		r0 = returnFunc(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []T) error); ok {
		r1 = returnFunc(ctx, models)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockRepository_SaveMany_Call[T any] struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []T
func (_e *MockRepository_Expecter[T]) SaveMany(ctx any, models any) *MockRepository_SaveMany_Call[T] {
	return &MockRepository_SaveMany_Call[T]{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockRepository_SaveMany_Call[T]) Run(run func(ctx context.Context, models []T)) *MockRepository_SaveMany_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []T
		if args[1] != nil {
			arg1 = args[1].([]T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveMany_Call[T]) Return(vs []T, err error) *MockRepository_SaveMany_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockRepository_SaveMany_Call[T]) RunAndReturn(run func(ctx context.Context, models []T) ([]T, error)) *MockRepository_SaveMany_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Update(ctx context.Context, model T) (T, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) (T, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) T); ok {
		r0 = returnFunc(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call[T any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model T
func (_e *MockRepository_Expecter[T]) Update(ctx any, model any) *MockRepository_Update_Call[T] {
	return &MockRepository_Update_Call[T]{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockRepository_Update_Call[T]) Run(run func(ctx context.Context, model T)) *MockRepository_Update_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call[T]) Return(v T, err error) *MockRepository_Update_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_Update_Call[T]) RunAndReturn(run func(ctx context.Context, model T) (T, error)) *MockRepository_Update_Call[T] {
	_c.Call.Return(run)
	return _c
}
