// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/yunobar/album/internal/domain/dto"
)

// NewMockWatchlistService creates a new instance of MockWatchlistService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchlistService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchlistService {
	mock := &MockWatchlistService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchlistService is an autogenerated mock type for the WatchlistService type
type MockWatchlistService struct {
	mock.Mock
}

type MockWatchlistService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchlistService) EXPECT() *MockWatchlistService_Expecter {
	return &MockWatchlistService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockWatchlistService
func (_mock *MockWatchlistService) Add(ctx context.Context, profileID uuid.UUID, request dto.AddWatchlistItemRequest) (dto.WatchlistItemResponse, error) {
	ret := _mock.Called(ctx, profileID, request)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 dto.WatchlistItemResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AddWatchlistItemRequest) (dto.WatchlistItemResponse, error)); ok {
		return returnFunc(ctx, profileID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AddWatchlistItemRequest) dto.WatchlistItemResponse); ok {
		r0 = returnFunc(ctx, profileID, request)
	} else {
		r0 = ret.Get(0).(dto.WatchlistItemResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.AddWatchlistItemRequest) error); ok {
		r1 = returnFunc(ctx, profileID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWatchlistService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockWatchlistService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - request dto.AddWatchlistItemRequest
func (_e *MockWatchlistService_Expecter) Add(ctx any, profileID any, request any) *MockWatchlistService_Add_Call {
	return &MockWatchlistService_Add_Call{Call: _e.mock.On("Add", ctx, profileID, request)}
}

func (_c *MockWatchlistService_Add_Call) Run(run func(ctx context.Context, profileID uuid.UUID, request dto.AddWatchlistItemRequest)) *MockWatchlistService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.AddWatchlistItemRequest
		if args[2] != nil {
			arg2 = args[2].(dto.AddWatchlistItemRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWatchlistService_Add_Call) Return(watchlistItemResponse dto.WatchlistItemResponse, err error) *MockWatchlistService_Add_Call {
	_c.Call.Return(watchlistItemResponse, err)
	return _c
}

func (_c *MockWatchlistService_Add_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID, request dto.AddWatchlistItemRequest) (dto.WatchlistItemResponse, error)) *MockWatchlistService_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWatchlistService
func (_mock *MockWatchlistService) List(ctx context.Context, profileID uuid.UUID) ([]dto.WatchlistItemResponse, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.WatchlistItemResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.WatchlistItemResponse, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.WatchlistItemResponse); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.WatchlistItemResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWatchlistService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWatchlistService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
func (_e *MockWatchlistService_Expecter) List(ctx any, profileID any) *MockWatchlistService_List_Call {
	return &MockWatchlistService_List_Call{Call: _e.mock.On("List", ctx, profileID)}
}

func (_c *MockWatchlistService_List_Call) Run(run func(ctx context.Context, profileID uuid.UUID)) *MockWatchlistService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWatchlistService_List_Call) Return(watchlistItemResponses []dto.WatchlistItemResponse, err error) *MockWatchlistService_List_Call {
	_c.Call.Return(watchlistItemResponses, err)
	return _c
}

func (_c *MockWatchlistService_List_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID) ([]dto.WatchlistItemResponse, error)) *MockWatchlistService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockWatchlistService
func (_mock *MockWatchlistService) Remove(ctx context.Context, profileID uuid.UUID, contentID uuid.UUID) error {
	ret := _mock.Called(ctx, profileID, contentID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, profileID, contentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatchlistService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockWatchlistService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - contentID uuid.UUID
func (_e *MockWatchlistService_Expecter) Remove(ctx any, profileID any, contentID any) *MockWatchlistService_Remove_Call {
	return &MockWatchlistService_Remove_Call{Call: _e.mock.On("Remove", ctx, profileID, contentID)}
}

func (_c *MockWatchlistService_Remove_Call) Run(run func(ctx context.Context, profileID uuid.UUID, contentID uuid.UUID)) *MockWatchlistService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWatchlistService_Remove_Call) Return(err error) *MockWatchlistService_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatchlistService_Remove_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID, contentID uuid.UUID) error) *MockWatchlistService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockWatchlistService
func (_mock *MockWatchlistService) Update(ctx context.Context, profileID uuid.UUID, contentID uuid.UUID, request dto.UpdateWatchlistItemRequest) (dto.WatchlistItemResponse, error) {
	ret := _mock.Called(ctx, profileID, contentID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.WatchlistItemResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateWatchlistItemRequest) (dto.WatchlistItemResponse, error)); ok {
		return returnFunc(ctx, profileID, contentID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateWatchlistItemRequest) dto.WatchlistItemResponse); ok {
		r0 = returnFunc(ctx, profileID, contentID, request)
	} else {
		r0 = ret.Get(0).(dto.WatchlistItemResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateWatchlistItemRequest) error); ok {
		r1 = returnFunc(ctx, profileID, contentID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWatchlistService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWatchlistService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - contentID uuid.UUID
//   - request dto.UpdateWatchlistItemRequest
func (_e *MockWatchlistService_Expecter) Update(ctx any, profileID any, contentID any, request any) *MockWatchlistService_Update_Call {
	return &MockWatchlistService_Update_Call{Call: _e.mock.On("Update", ctx, profileID, contentID, request)}
}

func (_c *MockWatchlistService_Update_Call) Run(run func(ctx context.Context, profileID uuid.UUID, contentID uuid.UUID, request dto.UpdateWatchlistItemRequest)) *MockWatchlistService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.UpdateWatchlistItemRequest
		if args[3] != nil {
			arg3 = args[3].(dto.UpdateWatchlistItemRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWatchlistService_Update_Call) Return(watchlistItemResponse dto.WatchlistItemResponse, err error) *MockWatchlistService_Update_Call {
	_c.Call.Return(watchlistItemResponse, err)
	return _c
}

func (_c *MockWatchlistService_Update_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID, contentID uuid.UUID, request dto.UpdateWatchlistItemRequest) (dto.WatchlistItemResponse, error)) *MockWatchlistService_Update_Call {
	_c.Call.Return(run)
	return _c
}
