// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yunobar/album/internal/domain/client"
)

// NewMockTMDBClient creates a new instance of MockTMDBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTMDBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTMDBClient {
	mock := &MockTMDBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTMDBClient is an autogenerated mock type for the TMDBClient type
type MockTMDBClient struct {
	mock.Mock
}

type MockTMDBClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTMDBClient) EXPECT() *MockTMDBClient_Expecter {
	return &MockTMDBClient_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type MockTMDBClient
func (_mock *MockTMDBClient) Search(ctx context.Context, query string) ([]client.TMDBResult, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []client.TMDBResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]client.TMDBResult, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []client.TMDBResult); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.TMDBResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTMDBClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockTMDBClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockTMDBClient_Expecter) Search(ctx any, query any) *MockTMDBClient_Search_Call {
	return &MockTMDBClient_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockTMDBClient_Search_Call) Run(run func(ctx context.Context, query string)) *MockTMDBClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTMDBClient_Search_Call) Return(tMDBResults []client.TMDBResult, err error) *MockTMDBClient_Search_Call {
	_c.Call.Return(tMDBResults, err)
	return _c
}

func (_c *MockTMDBClient_Search_Call) RunAndReturn(run func(ctx context.Context, query string) ([]client.TMDBResult, error)) *MockTMDBClient_Search_Call {
	_c.Call.Return(run)
	return _c
}
